name: GitHub Stats

on:
  schedule:
    - cron: '0 3 * * *'   # se ejecuta todos los d√≠as a las 03:00 UTC
  workflow_dispatch:       # te permite lanzarlo a mano desde Actions

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate the user stats image
        uses: cicirello/user-statistician@v1
        with:
          colors: dark-dimmed          # tema oscuro tipo GitHub
          custom-title: "GitHub stats de MILLERMARRU"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
